# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_stages = ["pre-commit"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace", priority = 0 },
  { id = "end-of-file-fixer", priority = 0 },
  { id = "check-yaml", priority = 0 },
  { id = "check-toml", priority = 0 },
]

[[repos]]
repo = "local"
hooks = [
  { id = "check", name = "vp check", entry = "vp check", language = "system", pass_filenames = false, priority = 10 },
  { id = "typecheck", name = "vp run typecheck", entry = "vp run typecheck", language = "system", pass_filenames = false, priority = 20 },
  { id = "test", name = "vp run --filter './packages/*' test", entry = "vp run --filter './packages/*' test", language = "system", pass_filenames = false, priority = 30 },
]
