import { defineConfig } from "vite-plus";

// lint / fmt の設定を vite-plus の設定ファイルに統一する
export default defineConfig({
  lint: {
    plugins: ["typescript", "oxc", "unicorn", "import", "promise", "vitest"],
    categories: {
      correctness: "error",
      perf: "error",
      suspicious: "error",
      pedantic: "error",
      restriction: "off",
      style: "error",
    },
    rules: {
      "no-console": "error",
      "no-debugger": "error",
      "no-alert": "error",
      "no-eval": "error",
      "no-new-func": "error",
      "no-script-url": "error",
      "no-void": "error",
      "no-with": "error",
      eqeqeq: "error",
      "no-var": "error",
      curly: "error",
      "guard-for-in": "error",
      "no-caller": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-iterator": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-multi-str": "error",
      "no-new-wrappers": "error",
      "no-proto": "error",
      "no-return-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-throw-literal": "error",
      "no-unused-expressions": "error",
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "sort-imports": [
        "error",
        {
          ignoreDeclarationSort: true,
        },
      ],
      "prefer-exponentiation-operator": "error",
      "prefer-object-spread": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      radix: "error",
      "symbol-description": "error",
      complexity: [
        "error",
        {
          max: 20,
        },
      ],
      "max-statements": [
        "error",
        {
          max: 50,
        },
      ],
      "no-await-in-loop": "error",
      "array-callback-return": "error",
      "no-constructor-return": "error",
      "no-promise-executor-return": "error",
      "no-prototype-builtins": "error",
      "block-scoped-var": "error",
      "no-new": "error",
      "no-useless-constructor": "error",
      "default-case-last": "error",
      "default-param-last": "error",
      "grouped-accessor-pairs": "error",
      "no-useless-computed-key": "error",
      "no-duplicate-imports": "error",
      "prefer-object-has-own": "error",
      "prefer-numeric-literals": "error",
      "arrow-body-style": "error",
      yoda: "error",
      "no-else-return": "error",
      "no-negated-condition": "error",
      "no-object-constructor": "error",
      "no-useless-return": "error",
      "no-param-reassign": "error",
      "class-methods-use-this": "error",
      "typescript/await-thenable": "error",
      "typescript/no-array-delete": "error",
      "typescript/no-base-to-string": "error",
      "typescript/no-confusing-void-expression": "error",
      "typescript/no-deprecated": "error",
      "typescript/no-duplicate-type-constituents": "error",
      "typescript/no-floating-promises": "error",
      "typescript/no-for-in-array": "error",
      "typescript/no-implied-eval": "error",
      "typescript/no-meaningless-void-operator": "error",
      "typescript/no-misused-promises": "error",
      "typescript/no-misused-spread": "error",
      "typescript/no-mixed-enums": "error",
      "typescript/no-redundant-type-constituents": "error",
      "typescript/no-unnecessary-boolean-literal-compare": "error",
      "typescript/no-unnecessary-template-expression": "error",
      "typescript/no-unnecessary-type-arguments": "error",
      "typescript/no-unnecessary-type-assertion": "error",
      "typescript/no-unsafe-argument": "error",
      "typescript/no-unsafe-assignment": "error",
      "typescript/no-unsafe-call": "error",
      "typescript/no-unsafe-enum-comparison": "error",
      "typescript/no-unsafe-member-access": "error",
      "typescript/no-unsafe-return": "error",
      "typescript/no-unsafe-type-assertion": "error",
      "typescript/no-unsafe-unary-minus": "error",
      "typescript/prefer-optional-chain": "error",
      "typescript/non-nullable-type-assertion-style": "error",
      "typescript/only-throw-error": "error",
      "typescript/prefer-includes": "error",
      "typescript/prefer-nullish-coalescing": "error",
      "typescript/prefer-promise-reject-errors": "error",
      "typescript/prefer-reduce-type-parameter": "error",
      "typescript/prefer-return-this-type": "error",
      "typescript/promise-function-async": "error",
      "typescript/related-getter-setter-pairs": "error",
      "typescript/require-array-sort-compare": "error",
      "typescript/require-await": "error",
      "typescript/restrict-plus-operands": "error",
      "typescript/restrict-template-expressions": "error",
      "typescript/return-await": "error",
      "typescript/strict-boolean-expressions": "error",
      "typescript/switch-exhaustiveness-check": "error",
      "typescript/unbound-method": "error",
      "typescript/use-unknown-in-catch-callback-variable": "error",
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-extra-non-null-assertion": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-non-null-assertion": "error",
      "typescript/no-this-alias": "error",
      "typescript/prefer-as-const": "error",
      "typescript/prefer-for-of": "error",
      "typescript/prefer-function-type": "error",
      "typescript/prefer-literal-enum-member": "error",
      "typescript/consistent-indexed-object-style": ["error", "record"],
      "typescript/consistent-type-definitions": ["error", "interface"],
      "typescript/consistent-type-imports": "error",
      "typescript/array-type": [
        "error",
        {
          default: "array-simple",
        },
      ],
      "typescript/ban-ts-comment": [
        "error",
        {
          "ts-expect-error": "allow-with-description",
        },
      ],
      "typescript/ban-tslint-comment": "error",
      "typescript/explicit-function-return-type": "error",
      "typescript/no-confusing-non-null-assertion": "error",
      "typescript/no-dynamic-delete": "error",
      "typescript/no-empty-object-type": "error",
      "typescript/no-extraneous-class": "error",
      "typescript/no-import-type-side-effects": "error",
      "typescript/no-inferrable-types": "error",
      "typescript/no-invalid-void-type": "error",
      "typescript/no-namespace": "error",
      "typescript/no-require-imports": "error",
      "typescript/no-useless-empty-export": "error",
      "typescript/no-wrapper-object-types": "error",
      "typescript/no-unsafe-declaration-merging": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/prefer-enum-initializers": "error",
      "typescript/prefer-namespace-keyword": "error",
      "typescript/triple-slash-reference": "error",
      "typescript/adjacent-overload-signatures": "error",
      "typescript/consistent-generic-constructors": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "typescript/prefer-readonly-parameter-types": "off",
      "oxc/approx-constant": "error",
      "oxc/bad-array-method-on-arguments": "error",
      "oxc/bad-bitwise-operator": "error",
      "oxc/bad-char-at-comparison": "error",
      "oxc/bad-comparison-sequence": "error",
      "oxc/bad-min-max-func": "error",
      "oxc/bad-object-literal-comparison": "error",
      "oxc/bad-replace-all-arg": "error",
      "oxc/const-comparisons": "error",
      "oxc/double-comparisons": "error",
      "oxc/erasing-op": "error",
      "oxc/misrefactored-assign-op": "error",
      "oxc/missing-throw": "error",
      "oxc/no-accumulating-spread": "error",
      "oxc/number-arg-out-of-range": "error",
      "oxc/only-used-in-recursion": "error",
      "oxc/uninvoked-array-callback": "error",
      "oxc/no-map-spread": "error",
      "unicorn/catch-error-name": "error",
      "unicorn/consistent-empty-array-spread": "error",
      "unicorn/consistent-existence-index-check": "error",
      "unicorn/consistent-function-scoping": "error",
      "unicorn/consistent-date-clone": "error",
      "unicorn/error-message": "error",
      "unicorn/escape-case": "error",
      "unicorn/explicit-length-check": "error",
      "unicorn/new-for-builtins": "error",
      "unicorn/no-abusive-eslint-disable": "error",
      "unicorn/no-accessor-recursion": "error",
      "unicorn/no-array-callback-reference": "error",
      "unicorn/no-array-for-each": "error",
      "unicorn/no-array-method-this-argument": "error",
      "unicorn/no-array-reduce": "error",
      "unicorn/no-await-expression-member": "error",
      "unicorn/no-await-in-promise-methods": "error",
      "unicorn/no-empty-file": "error",
      "unicorn/no-hex-escape": "error",
      "unicorn/no-immediate-mutation": "error",
      "unicorn/no-instanceof-array": "error",
      "unicorn/no-instanceof-builtins": "error",
      "unicorn/no-invalid-fetch-options": "error",
      "unicorn/no-length-as-slice-end": "error",
      "unicorn/no-lonely-if": "error",
      "unicorn/no-magic-array-flat-depth": "error",
      "unicorn/no-negation-in-equality-check": "error",
      "unicorn/no-nested-ternary": "error",
      "unicorn/no-new-array": "error",
      "unicorn/no-new-buffer": "error",
      "unicorn/no-null": "off",
      "unicorn/no-object-as-default-parameter": "error",
      "unicorn/no-single-promise-in-promise-methods": "error",
      "unicorn/no-static-only-class": "error",
      "unicorn/no-thenable": "error",
      "unicorn/no-this-assignment": "error",
      "unicorn/no-typeof-undefined": "error",
      "unicorn/no-unnecessary-await": "error",
      "unicorn/no-unnecessary-slice-end": "error",
      "unicorn/no-unreadable-array-destructuring": "error",
      "unicorn/no-unreadable-iife": "error",
      "unicorn/no-useless-fallback-in-spread": "error",
      "unicorn/no-useless-length-check": "error",
      "unicorn/no-useless-promise-resolve-reject": "error",
      "unicorn/no-useless-spread": "error",
      "unicorn/no-useless-switch-case": "error",
      "unicorn/no-useless-undefined": "error",
      "unicorn/no-zero-fractions": "error",
      "unicorn/number-literal-case": "off",
      "unicorn/numeric-separators-style": "error",
      "unicorn/prefer-array-find": "error",
      "unicorn/prefer-array-flat-map": "error",
      "unicorn/prefer-array-flat": "error",
      "unicorn/prefer-array-index-of": "error",
      "unicorn/prefer-array-some": "error",
      "unicorn/prefer-at": "error",
      "unicorn/prefer-code-point": "error",
      "unicorn/prefer-date-now": "error",
      "unicorn/prefer-default-parameters": "error",
      "unicorn/prefer-global-this": "error",
      "unicorn/prefer-logical-operator-over-ternary": "error",
      "unicorn/prefer-math-min-max": "error",
      "unicorn/prefer-math-trunc": "error",
      "unicorn/prefer-modern-math-apis": "error",
      "unicorn/prefer-native-coercion-functions": "error",
      "unicorn/prefer-negative-index": "error",
      "unicorn/prefer-number-properties": "error",
      "unicorn/prefer-object-from-entries": "error",
      "unicorn/prefer-optional-catch-binding": "error",
      "unicorn/prefer-prototype-methods": "error",
      "unicorn/prefer-reflect-apply": "error",
      "unicorn/prefer-regexp-test": "error",
      "unicorn/prefer-set-has": "error",
      "unicorn/prefer-set-size": "error",
      "unicorn/prefer-spread": "error",
      "unicorn/prefer-string-raw": "error",
      "unicorn/prefer-string-replace-all": "error",
      "unicorn/prefer-string-slice": "error",
      "unicorn/prefer-string-starts-ends-with": "error",
      "unicorn/prefer-string-trim-start-end": "error",
      "unicorn/prefer-structured-clone": "error",
      "unicorn/prefer-top-level-await": "error",
      "unicorn/prefer-type-error": "error",
      "unicorn/require-array-join-separator": "error",
      "unicorn/require-module-attributes": "error",
      "unicorn/require-number-to-fixed-digits-argument": "error",
      "unicorn/switch-case-braces": "error",
      "unicorn/text-encoding-identifier-case": "error",
      "unicorn/throw-new-error": "error",
      "unicorn/consistent-assert": "error",
      "unicorn/prefer-class-fields": "error",
      "unicorn/no-anonymous-default-export": "error",
      "import/default": "error",
      "import/export": "error",
      "import/first": "error",
      "import/named": "error",
      "import/namespace": "error",
      "import/no-absolute-path": "error",
      "import/no-amd": "error",
      "import/no-commonjs": "error",
      "import/no-cycle": "error",
      "import/no-duplicates": "error",
      "import/no-empty-named-blocks": "error",
      "import/no-mutable-exports": "error",
      "import/no-named-as-default": "error",
      "import/no-named-as-default-member": "error",
      "import/no-named-default": "error",
      "import/no-self-import": "error",
      "import/no-webpack-loader-syntax": "error",
      "import/unambiguous": "error",
      "import/exports-last": "error",
      "promise/always-return": "error",
      "promise/avoid-new": "off",
      "promise/catch-or-return": "error",
      "promise/no-callback-in-promise": "error",
      "promise/no-multiple-resolved": "error",
      "promise/no-nesting": "error",
      "promise/no-new-statics": "error",
      "promise/no-promise-in-callback": "error",
      "promise/no-return-in-finally": "error",
      "promise/no-return-wrap": "error",
      "promise/param-names": "error",
      "promise/prefer-await-to-callbacks": "error",
      "promise/prefer-await-to-then": "error",
      "promise/prefer-catch": "error",
      "promise/valid-params": "error",
      "vitest/warn-todo": "error",
      "vitest/consistent-vitest-vi": "error",
      "vitest/consistent-each-for": "error",
      "vitest/hoisted-apis-on-top": "error",
      "vitest/no-unneeded-async-expect-function": "error",
      "vitest/prefer-called-times": "error",
      "vitest/prefer-called-once": "error",
      "vitest/prefer-spy-on": "error",
      "vitest/prefer-describe-function-title": "error",
      "vitest/prefer-to-have-been-called-times": "error",
      "vitest/prefer-called-with": "error",
      "vitest/consistent-test-filename": "error",
      "vitest/require-hook": "error",
      "react/no-did-mount-set-state": "error",
      "react/no-will-update-set-state": "error",
      "react/no-unsafe": "error",
      "react/no-this-in-sfc": "error",
      "react/jsx-key": "error",
      "react/jsx-no-duplicate-props": "error",
      "react/jsx-no-undef": "error",
      "react/jsx-props-no-spread-multi": "error",
      "react/no-children-prop": "error",
      "react/no-danger-with-children": "error",
      "react/void-dom-elements-no-children": "error",
      "react/rules-of-hooks": "error",
      "react/exhaustive-deps": "error",
      "react/jsx-no-target-blank": "error",
      "react/jsx-no-script-url": "error",
      "react/iframe-missing-sandbox": "error",
      "react/no-danger": "error",
      "react/jsx-no-comment-textnodes": "error",
      "react/no-unescaped-entities": "error",
      "react/style-prop-object": "error",
      "react/jsx-no-useless-fragment": "error",
      "react/button-has-type": "error",
      "react/jsx-boolean-value": "error",
      "react/jsx-curly-brace-presence": "error",
      "react/jsx-fragments": "error",
      "react/jsx-pascal-case": "error",
      "react/self-closing-comp": "error",
      "react/react-in-jsx-scope": "off",
      "capitalized-comments": "off",
      "sort-keys": "off",
    },
    overrides: [
      {
        files: ["**/*.test.ts", "**/*.prop.ts"],
        rules: {
          "typescript/no-explicit-any": "off",
          "typescript/no-non-null-assertion": "off",
          "typescript/no-unsafe-argument": "off",
          "typescript/no-unsafe-assignment": "off",
          "typescript/no-unsafe-call": "off",
          "typescript/no-unsafe-member-access": "off",
          "typescript/no-unsafe-return": "off",
          "typescript/no-unsafe-type-assertion": "off",
          "vitest/prefer-lowercase-title": "off",
          "vitest/prefer-describe-function-title": "off",
          "vitest/no-importing-vitest-globals": "off",
          "vitest/prefer-expect-type-of": "off",
          "vitest/prefer-expect-assertions": "off",
          "unicorn/filename-case": "off",
        },
      },
      {
        files: ["**/vite.config.*"],
        rules: {
          "import/exports-last": "off",
          "import/no-nodejs-modules": "off",
          "no-ternary": "off",
          "typescript/explicit-function-return-type": "off",
          "typescript/no-unsafe-argument": "off",
          "typescript/no-unsafe-assignment": "off",
          "typescript/no-unsafe-call": "off",
          "typescript/no-unsafe-member-access": "off",
          "typescript/no-unsafe-return": "off",
          "no-underscore-dangle": "off",
          "max-lines": "off",
          "capitalized-comments": "off",
          "sort-keys": "off",
        },
      },
      {
        files: ["**/*.d.ts"],
        rules: {
          "id-length": "off",
          "import/group-exports": "off",
          "import/no-named-export": "off",
          "import/unambiguous": "off",
          "max-params": "off",
        },
      },
      {
        files: ["examples/**/*.ts"],
        rules: {
          "func-style": "off",
          "id-length": "off",
          "init-declarations": "off",
          "max-lines-per-function": "off",
          "no-alert": "off",
          "no-magic-numbers": "off",
          "no-shadow": "off",
          "no-void": "off",
          "prefer-destructuring": "off",
          "require-await": "off",
          "import/no-named-export": "off",
          "promise/always-return": "off",
          "promise/no-nesting": "off",
          "promise/prefer-await-to-then": "off",
          "typescript/explicit-function-return-type": "off",
          "typescript/no-misused-promises": "off",
          "typescript/no-non-null-assertion": "off",
          "typescript/no-unsafe-argument": "off",
          "typescript/no-unsafe-assignment": "off",
          "typescript/no-unsafe-call": "off",
          "typescript/no-unsafe-member-access": "off",
          "typescript/require-await": "off",
          "typescript/strict-boolean-expressions": "off",
          "unicorn/consistent-function-scoping": "off",
          "unicorn/no-array-for-each": "off",
          "unicorn/numeric-separators-style": "off",
          "unicorn/prefer-global-this": "off",
          "unicorn/prefer-query-selector": "off",
          "vitest/require-hook": "off",
          "typescript/no-unnecessary-boolean-literal-compare": "off",
          "typescript/no-useless-default-assignment": "off",
          "typescript/prefer-nullish-coalescing": "off",
          "typescript/no-unsafe-type-assertion": "off",
          "typescript/no-unnecessary-type-assertion": "off",
        },
      },
      {
        files: ["**/*.js"],
        rules: {
          "id-length": "off",
          "no-magic-numbers": "off",
          "prefer-destructuring": "off",
          "import/unambiguous": "off",
          "typescript/no-unsafe-argument": "off",
          "typescript/no-unsafe-assignment": "off",
          "typescript/no-unsafe-call": "off",
          "typescript/no-unsafe-member-access": "off",
          "unicorn/filename-case": "off",
          "unicorn/prefer-add-event-listener": "off",
          "vitest/require-hook": "off",
        },
      },
      {
        files: ["packages/*/src/**/*.ts"],
        rules: {
          "no-magic-numbers": "off",
          "id-length": "off",
          "unicorn/filename-case": "off",
          "func-style": "off",
          "max-lines-per-function": "off",
          "max-lines": "off",
          "max-classes-per-file": "off",
          "max-params": "off",
          "no-inline-comments": "off",
          "no-warning-comments": "off",
          "no-void": "off",
          "init-declarations": "off",
          "no-negated-condition": "off",
          "import/no-named-export": "off",
          "import/no-namespace": "off",
          "import/prefer-default-export": "off",
          "promise/no-nesting": "off",
          "promise/prefer-await-to-callbacks": "off",
          "promise/prefer-await-to-then": "off",
          "unicorn/prefer-global-this": "off",
          "no-console": "off",
          "no-shadow": "off",
          "no-await-in-loop": "off",
          "require-await": "off",
          "typescript/require-await": "off",
          "typescript/no-unsafe-type-assertion": "off",
          "typescript/no-unsafe-call": "off",
          "typescript/no-unsafe-assignment": "off",
          "typescript/no-unsafe-argument": "off",
          "typescript/no-unsafe-return": "off",
          "typescript/use-unknown-in-catch-callback-variable": "off",
          "typescript/strict-boolean-expressions": "off",
          "typescript/no-non-null-assertion": "off",
          "no-duplicate-imports": "off",
          "class-methods-use-this": "off",
          "typescript/explicit-function-return-type": "off",
          "typescript/ban-ts-comment": "off",
          "unicorn/no-await-expression-member": "off",
          "unicorn/prefer-ternary": "off",
          "unicorn/no-negated-condition": "off",
        },
      },
    ],
    ignorePatterns: ["dist/**", "node_modules/**"],
  },
  fmt: {
    ignorePatterns: ["dist/**"],
  },
});
