name: ci

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "NOTICE"

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node:
          - "26"
          - "24"
          - "22"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: rustup update stable && rustup target add wasm32-unknown-unknown
      - uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1.15.0
        with:
          node-version: ${{ matrix.node }}
          run-install: false
      - run: vp --version
      - run: vp install
      - run: vp run build
      - run: vp run lint
      - run: vp run typecheck
      - run: vp run test

  slack_notify:
    needs: [ci]
    runs-on: ubuntu-slim
    if: ${{ !cancelled() }}
    permissions:
      actions: read
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: media-processors
          notify_mode: failure_and_fixed
