name: ci

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "NOTICE"
    # branches-ignore:
    #   - "feature/pnpm"

jobs:
  ci:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node: ["20", "22", "24"]
    steps:
      - uses: actions/checkout@v6
      - run: rustup update stable && rustup target add wasm32-unknown-unknown
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm --version
      - run: pnpm install
      - run: pnpm run typecheck
      - run: pnpm run build
      - run: pnpm run lint
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: media-processors
          SLACK_COLOR: danger
          SLACK_TITLE: Failure test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
