name: GitHub Pages Deploy

on:
  push:
    branches: ["develop"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: rustup update stable && rustup target add wasm32-unknown-unknown
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - uses: pnpm/action-setup@v5
      - run: pnpm install
      - name: Build
        run: pnpm build
      - name: Build examples
        run: pnpm build
        working-directory: examples
      - name: Upload files
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./examples/dist
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  slack_notify:
    needs: [build, deploy]
    runs-on: ubuntu-slim
    if: ${{ !cancelled() }}
    permissions:
      actions: read
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: media-processors
          notify_mode: failure_and_fixed
