name: release

on:
  push:
    tags:
      - '*'

jobs:
  create-release-draft:
    name: Create GitHub Release Draft
    runs-on: ubuntu-24.04
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: true

  notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs:
      - create-release-draft
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: rtCamp/action-slack-notify@v2
        if: |
          needs.create-release-draft.result == 'failure'
        env:
          SLACK_CHANNEL: media-processors
          SLACK_COLOR: danger
          SLACK_TITLE: Failure release
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
