name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  create-release-draft:
    name: Create GitHub Release Draft
    runs-on: ubuntu-24.04
    steps:
      - name: Create release draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --draft --title "${{ github.ref_name }}" --repo "${{ github.repository }}"

  slack_notify:
    needs: [create-release-draft]
    runs-on: ubuntu-slim
    if: ${{ !cancelled() }}
    permissions:
      actions: read
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: media-processors
          notify_mode: failure_and_fixed
